# Generated by Django 5.1.6 on 2025-07-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='core_value_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='core_value_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='cta_primary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='cta_secondary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='impact_stat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='home',
            name='newsletter_prompt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='subline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='home',
            name='testimonial',
            field=models.TextField(blank=True),
        ),
    ]
